## Функции. Рекурсия.


### Упражение 1
Написать функцию, считающую N-ое число Фибоначчи (N вводится с клавиатуры).

### Упражение 2
Написать функцию, раскладывающую число на простые множители (число вводится с клавиатуры).


### Упражнение 3
Со времен Евклида известно, что для любых положительных a и b существуют такие целые x и y, что ax + by = d, где d – наибольший общий делитель a и b. По заданным a и b найти x, y, d.

Вход. Каждая строка содержит два натуральных числа a и b, разделенных пробелом.

Выход. Для каждой пары a и b в отдельной строке вывести три целых числа x, y и d, разделенных пробелом. Если искомых значений x и y несколько, то следует выводить такую пару, для которой |x| + |y| минимально. Если и таких пар несколько, то вывести ту пару, в которой x минимально.

|Пример входа|Пример выхода|
|-|-|
|4 6|-1 1 2|
|17 17|0 1 17|
|5 3|-1 2 1|



### Упражнение 4
Напишите функцию для вывода треугольника. Функция принимает два аргумента – size (количество строк, на которых будет строиться треугольник) и symb (символ, используемый для заполнения треугольника).

Пример входа: `7 c`

Пример выхода:





In [11]:
"""Exercise 1."""


def fib(n):
    """Return n-th Fibonacci number."""
    if n <= 1:
        return n

    return fib(n - 1) + fib(n - 2)


n = int(input())
print(fib(n))


5
5


In [12]:
"""Exercise 2."""


def factors(n):
    """Return prime factors of n."""
    a = []
    d = 2

    while d * d <= n:
        while n % d == 0:
            a.append(d)
            n //= d
        d += 1

    if n > 1:
        a.append(n)

    return a


n = int(input())
print(*factors(n))


100
2 2 5 5


In [14]:
"""Exercise 3."""


def euclid(a, b):
    """Find x y and gcd."""
    if b == 0:
        return 1, 0, a

    x, y, d = euclid(b, a % b)
    return y, x - a // b * y, d


a, b = map(int, input().split())
x, y, d = euclid(a, b)
print(x, y, d)


5 30
1 0 5


In [26]:
"""Exercise 4."""


def triangle(size, symb, i=0):
    """Print triangle recursively."""
    if i == size:
        return

    if i < (size + 1) // 2:
        print(symb * (i + 1))
    else:
        print(symb * (size - i))

    triangle(size, symb, i + 1)


size, symb = input().split()
triangle(int(size), symb)


7 c
c
cc
ccc
cccc
ccc
cc
c


## Библиотеки. Numpy

Для решения практических задач часто бывает необходимо
Для вычисления математических функций в python есть стандартная библиотека [math](http://docs.scipy.org/doc/numpy/reference/generated/numpy.log.html#numpy.log). Однако значительно более сильным инструментом является библиотека [numpy](http://docs.scipy.org/doc/numpy/reference/generated/numpy.polyfit.html).
Данная библиотека обеспечивает удобную работу с векторами, которые здесь наззываются массивами (arrays).

Т.е., если у нас есть массив X и мы вызовем numpy.log(x), то логарифм будет взят от каждого элемента и возвращен будет массив значений логарифмов элементов.

Традиционно библиотека numpy (как и любая другая) подключается командой:

``` python
import numpy
```
Пример вызова функции из библиотеки
``` python
numpy.cos(x)
```
Библиотеки можно подключить под псевдонимом:
``` python
import numpy as np
```
В таком случае мы можем вызывать функции так:
``` python
np.cos(x)
```
Такой код значительно проще читать и писать.

Возможно также подключать отдельные функции из библиотеки, это позволит вызывать их без указания названия библиотеки:
``` python
from numpy import cos
cos(x)
```
``` python
from numpy import cos
cos(x)
```

Как уже было сказано, основной объект, с которым принято взаимодействовать в numpy -- массивы. Они отличаются от списков тем, что могут хранить значения, имеющие один и тот же тип, и имеют определенные по-другому операции. Например:

``` python
a = np.array([1,2,3])
b = np.array([1,2,3])
c = a + b
```
Если бы `a` и `b` были списками, то мы получили бы "сшитый" список. Однако в данном случае мы получим результат поэлементного сложения двух массивов.

### *Broadcasting

Одной из фишек библиотеки numpy является [бродкастинг](https://numpy.org/doc/stable/user/basics.broadcasting.html). Он позволяет существенно упростить многие операции с массивами и матрицами. Самый простой пример бродкастинга:
```python
a = np.array([1,2,3,4])
b = 1
c = a + b
```
Казалось бы, мы должны получить ошибку, ведь массив и число -- разные типы данных. Однако в данном случае numpy поймет, что вы хотите прибавить единицу ко всем элементам массива и сделает это. Аналогично можно прибавлять к матрице вектор или строку соответствующего размера.

### Упражнение 5

Создайте матрицу размером `NxM`, заполненную "спиралью":

Умножьте каждую строку получившейся матрицы на номер строки, выведите результат.


### Упражнение 6

Напишите функцию, считающую коэффициенты МНК для набора измерений `x` и `y`.

### Упражнение 7

Напишите функцию, решающую линейную систему уравнений, заданную расширенной матрицей. На вход подаются `N` и `M` -- количество строк и столбцов расширенной матрицы, далее вводятся `N` строк, каждая из которых содержит `M` чисел.

### Упражнение 8* (для осн и продв)

Реализуйте функцию, генерирующую набор данных размером `N`, которые методом МНК аппроксимируются прямой с коэффициентами `a` и `b`. Для этого вам пригодится библиотека `random` и функция `random.gauss()`.



## *Функция eval()

В Python есть встроенная функция `eval()`, которая выполняет строку с
кодом и возвращает результат выполнения:

``` python
>>> eval("2 + 3*len('banana')")
20
```

Это очень мощная, но и довольно небезопасная команда.
Например, если строкой, которую мы передадим в `eval()`, окажется
`"os.system('rm -rf /')"` (в терминале Linux), то интерпретатор начнет удалять все файлы, включая системные, с компьютера.

## *Задачи по numpy для дополнительного изучения
https://github.com/rougier/numpy-100

In [27]:
"""Exercise 5."""

import numpy as np


n, m = map(int, input().split())
a = np.zeros((n, m), dtype=int)

x = 1
top = 0
bottom = n - 1
left = 0
right = m - 1

while top <= bottom and left <= right:
    for i in range(left, right + 1):
        a[top, i] = x
        x += 1
    top += 1

    for i in range(top, bottom + 1):
        a[i, right] = x
        x += 1
    right -= 1

    if top <= bottom:
        for i in range(right, left - 1, -1):
            a[bottom, i] = x
            x += 1
        bottom -= 1

    if left <= right:
        for i in range(bottom, top - 1, -1):
            a[i, left] = x
            x += 1
        left += 1

for i in range(n):
    a[i] *= i

print(a)


6 7
[[  0   0   0   0   0   0   0]
 [ 22  23  24  25  26  27   8]
 [ 42  72  74  76  78  56  18]
 [ 60 105 126 123 120  87  30]
 [ 76 136 132 128 124 120  44]
 [ 90  85  80  75  70  65  60]]


In [ ]:
"""Exercise 6."""

import numpy as np


def mnk(x, y):
    """Return coefficients a and b."""
    a, b = np.polyfit(x, y, 1)
    return a, b

In [ ]:
"""Exercise 7."""

import numpy as np


def solve(a):
    """Solve linear system."""
    x = np.linalg.solve(a[:, :-1], a[:, -1])
    return x


n, m = map(int, input().split())
a = np.array(
    [list(map(float, input().split())) for i in range(n)]
)

print(*solve(a))


In [30]:
"""Exercise 8."""

import random


def generate(n, a, b):
    """Generate data for line."""
    x = []
    y = []

    for i in range(n):
        x.append(i)
        y.append(random.gauss(a * i + b, 1))

    return x, y


n = int(input())
a, b = map(float, input().split())

x, y = generate(n, a, b)

print(x)
print(y)


10
5 2
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[3.7463901776659907, 6.7085249114967285, 11.445970502625189, 16.592289241385245, 20.018159769764168, 27.510197571994723, 31.873440621791758, 35.84382478654306, 40.25751804941938, 44.42298443685167]
